[package]
name = "gilgamesh"
version = "0.1.2"
edition = "2021"
description = "A small 3D rendering engine built upon WGPU with the primary goal of visualizing procedural terrains."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13.1"
cgmath = "0.18.0"
env_logger = "0.9.0"
futures = "0.3.21"
gfx-hal = "0.9.0"
image = "0.24.2"
log = "0.4.17"
pollster = "0.2.5"
winit = "0.26.1"
bytemuck = { version = "1.4.1", features = ["derive"] }
anyhow = "1.0.58"
rand = "0.8.5"
